image: ghcr.io/cirruslabs/macos-sonoma-xcode:15.3

variables:
  HOMEBREW_NO_AUTO_UPDATE: 1

stages:
  - CompileFramework
  - TestFrameworkBuild

CompileFramework:
  tags:
    - xcode
  stage: CompileFramework
  script:
    - brew install libtool autoconf automake pkgconfig coreutils bash zip swiftformat
    - /usr/sbin/softwareupdate --install-rosetta --agree-to-license
    - ./Scripts/build.sh clean
    - mv build/build.spm/ AppleMobileDeviceLibrary
    - mv build/build.binpack/binpack.tar .
    - cat binpack.tar | gzip > binpack.tar.gz
    - rm binpack.tar
    - mv src.version AppleMobileDeviceLibrary/.version
  artifacts:
    paths:
      - AppleMobileDeviceLibrary
      - binpack.tar.gz

TestFrameworkBuild:
  tags:
    - xcode
  stage: TestFrameworkBuild
  script:
    - cd AppleMobileDeviceLibrary
    - swift build
