image: ghcr.io/cirruslabs/macos-sonoma-xcode:15.1

variables:
  HOMEBREW_NO_AUTO_UPDATE: 1

stages:
- CompileFramework
- TestFrameworkBuild

CompileFramework:
  tags:
    - xcode
  only:
    variables:
    - $CI_PIPELINE_SOURCE == "web"
  stage: CompileFramework
  script:
    - brew install libtool autoconf automake pkgconfig coreutils bash zip swiftformat
    - ./Scripts/build.sh clean
    - mv build/build.spm/ AppleMobileDeviceLibrary
    - mv build/build.binpack/binpack.tar .
    - mv src.version AppleMobileDeviceLibrary/.version
  artifacts:
    paths:
    - AppleMobileDeviceLibrary
    - binpack.tar

TestFrameworkBuild:
  tags:
    - xcode
  only:
    variables:
    - $CI_PIPELINE_SOURCE == "web"
  stage: TestFrameworkBuild
  script:
    - cd AppleMobileDeviceLibrary
    - swift build
